server:
  port: 8080

avatar:
  upLoad-WinDir: D:/project/wedding/note/avatar
  upLoad-LinuxDir: /project/avatar

wechat:
  appid: wx31ee315b9a2305a9
  secret: 48bd4b3c2df1a8047669cc47c260f8a2
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  refreshTokenUrl: https://api.weixin.qq.com/sns/oauth2/refresh_token

spring:
  #  数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marrydb?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Mysql666.
#    password: 1234
    #    数据库连接池
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接池最大连接数
      maximum-pool-size: 10
      # 连接池最大生命周期
      max-lifetime: 1800000 # 30 minutes
      # 初始化时获取的连接数
      initializationFailTimeout: 1
      # 连接池初始化时预热连接
      connection-test-query: SELECT 1
      # 设置连接池初始化的时间（单位：毫秒）
      idle-timeout: 600000 # 10 minutes
      # 设置连接池最大等待时间
      connection-timeout: 30000 # 30 seconds

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: ""  # 如果有密码，填入密码
      database: 0
      timeout: 5000 # 连接超时，单位毫秒

      lettuce:
        pool:
          max-active: 8 #最大连接数（负数表示没有限制）
          max-wait: 1 #最大阻塞等待时间（负数表示没有限制）
          max-idle: 8 #最大空闲连接
          min-idle: 0 #最小空闲连接
    cache:
      type: redis

mybatis:
  type-aliases-package: com.ycu.wedding.pojo
  #  mapper-locations: com.ycu.wedding.mapper
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ycuql.school.mapper: trace
